### ISSUE TITLE
Why is .env.* ignored?

### ISSUE THREAD

**Issue by philbarbato** [fostermadeco/fm-website-starter#2]
Why is the `.env.*` pattern in .gitignore? It causes example .env files to be ignored. I don't want to assume I know better, so I'm curious if there's a strong reason for these files to be ignored.

**Comment by kellypacker** [comment]
I think the idea is that it's a catch all for the possibility of .env files that may have an env specific suffix. But it also ignores .env.sample which is not great. We could either do a .env-sample file or update the gitignore to just ignore .env.

**Comment by smaida** [comment]
@kellypacker Craft uses .env.example, so at a minimum we'll want to make sure that isn't ignored. 
https://github.com/craftcms/craft/blob/master/.env.example

**Comment by adam-winfree** [comment]
Just as an FYI, [Symfony no longer adds `.env` to `.gitignore`](https://symfony.com/doc/current/configuration/dot-env-changes.html). Older versions added `.env` to `.gitignore`, and used `.env.dist` as the template. We may want to consider removing `.env` from the list here.

**Comment by adam-winfree** [comment]
Also, a PHP framework may generate their own `.gitignore` which should take into consideration these sorts of things.

**Comment by kellypacker** [comment]
Since this is a cms specific starter, we have a web app specific starter, but it's all front-end, seems like we should keep .env in gitignore because Craft is the most likely use case. We can also add a note to the readme.
