### ISSUE TITLE
Is modernizr used anymore?

### ISSUE THREAD

**Issue by kellypacker** [fostermadeco/fm-website-starter#6]
@FMAndrew I know you used this the most. Is modernizr used anymore?

**Comment by FMAndrew** [comment]
I still use it, almost always only for touch detection so that :hover styles don't get applied to touch devices, etc.

**Comment by brianlarson** [comment]
Welp, I dint even know you could do that. Ah, the dreaded tablet viewports.

**Comment by kellypacker** [comment]
ok awesome. Good to know. Thanks!
